language: php

php:
  - 5.5
  - 7.0

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit -c app

notifications:
  email:
    -  nstepanovdev@gmail.com

script: phpunit -c app --verbose --colors --no-globals-backup